### ISSUE TITLE
Is this version of Playscii intended to build on 64-bit versions of Mac OS?

### ISSUE THREAD

**Issue by BrendanJercich** [michael-lazar/playscii#3]
Commentary on the Itch storefront seems to hint as much: https://itch.io/post/4747062 But I'm having trouble running it on Monterey/12.4. Specifically, I get the same error in response to `python3 playscii.py` on this repo that I do on the main repo from Heptapod, which is: 

```
Traceback (most recent call last):
  File "/Users/brendan/Library/Mobile Documents/com~apple~CloudDocs/Code/playscii-source/env/lib/python3.9/site-packages/sdl2/sdlmixer.py", line 79, in <module>
    dll = DLL("SDL2_mixer", ["SDL2_mixer", "SDL2_mixer-2.0"],
  File "/Users/brendan/Library/Mobile Documents/com~apple~CloudDocs/Code/playscii-source/env/lib/python3.9/site-packages/sdl2/dll.py", line 194, in __init__
    raise RuntimeError("could not find any library for %s (%s)" %
RuntimeError: could not find any library for SDL2_mixer (PYSDL2_DLL_PATH: .)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/brendan/Library/Mobile Documents/com~apple~CloudDocs/Code/playscii-source/playscii.py", line 31, in <module>
    from sdl2 import video, sdlmixer
  File "/Users/brendan/Library/Mobile Documents/com~apple~CloudDocs/Code/playscii-source/env/lib/python3.9/site-packages/sdl2/sdlmixer.py", line 82, in <module>
    raise ImportError(exc)
ImportError: could not find any library for SDL2_mixer (PYSDL2_DLL_PATH: .)
```

I have no experience with SDL, so I'm fumbling in the dark here, but I have tried setting the PYSDL2_DLL_PATH environment variable to point to (eg) the sdl2dll directory tucked away in python3.9/site-packages in this copy of the code, which doesn't seem to affect anything.

Are you able to run Playscii on 64-bit Mac OS? Have you seen this issue before?

**Comment by michael-lazar** [comment]
Greetings

The only changes that I made regarding building on a mac were bumping some of the python dependency versions. This was a while ago, but IIRC the Pillow version was so old that I was having trouble building / finding wheels on pypi for that package. 

https://github.com/michael-lazar/playscii/blame/master/requirements.txt

I'm currently running an M1 mac but I don't see any reason why this shouldn't work on 64-bit too. The installation notes that I wrote [here](https://github.com/michael-lazar/playscii/blob/master/NOTES.txt) are tailored to my specific environment and your homebrew directories or sdl version numbers might be different from mine.

I remember `PYSDL2_DLL_PATH` being a pain in the ass and finicky, and the key was that I had to create symlinks to the `.dylib` files and put them in the same directory.

https://github.com/michael-lazar/playscii/blob/2416e7438b993abd119a86b0fc1ffb1170eb33c3/NOTES.txt#L7-L8

I would double check that whatever your `PYSDL2_DLL_PATH` is set to, that directory contains both of these files with these specific names

- `libSDL2.dylib`
- `libSDL2_mixer.dylib`

**Comment by BrendanJercich** [comment]
OKAY! I had to tweak the paths to account for slightly different versions of the SDL libraries, and to account for my Homebrew libraries living in `/usr/local/Cellar/`, but after that following the instructions in the notes file actually launched the app from the command line. And I can add things to my virtual environment if I want to use them, too! Thank you very much!

**Comment by bknoles** [comment]
Using Python 3.10, I needed to bump numpy up to `1.21`. The `1.20` version wouldn't build a wheel with Python 3.10.  I didn't need to manually install Pillow either. My notes, based off [this very helpful guide](https://github.com/michael-lazar/playscii/blob/master/NOTES.txt).

```sh
# Install packages needed for the app
brew install sdl2 sdl2_mixer numpy libjpeg libtiff

# Find the paths to the dylib files by running:
brew list sdl2
brew list sdl2_mixer

# Symlink the dylib files into the project directory
# (note: if you ever upgrade the sdl2 libraries the symlinks presumably need to be updated)
ln -s /path/to/libSDL2-2.0.0.dylib libSDL2.dylib
ln -s /path/to/libSDL2_mixer-2.0.0.dylib libSDL2_mixer.dylib

# Change numpy version in `requirements.txt` to something compatible with your Python version.
# For me, numpy==1.21.6 worked fine with Python 3.10.6

# Setup up a virtual environment and install the required packages
python3 -m pip venv venv
source venv/bin/activate
pip install -r requirements.txt

# Run the program, specifying the current directory with symlinked dylib file as the path to the sdl2 libraries
PYSDL2_DLL_PATH=. python playscii.py

# Enjoy!
```

Leaving this here for the next poor soul with Python 3.10 that's trying to make art for their terminal CLIs 😅

Thanks @michael-lazar !

**Comment by sourencho** [comment]
After lots of trial and error I finally got the executable to run based on the instructions above but then I get the error below. Any ideas what could be the issue? 

```
(venv) ➜  playscii git:(master) ✗ python3 playscii.py
Playscii v9.16.3
Loading config from /Users/sourenpapazian/Library/Application Support/Playscii/playscii.cfg...
Config loaded.
Detecting hardware...
  CPU: arm
  GPU: Apple - Apple M1
  OpenGL detected: 4.1 Metal - 89.3
  GLSL detected: 4.10
  Vertex Array Object support found.
dict_keys([<class 'ctypes.c_int'>])
Traceback (most recent call last):
  File "/Users/sourenpapazian/Documents/code/extern/playscii/venv/lib/python3.13/site-packages/OpenGL/latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sourenpapazian/Documents/code/extern/playscii/playscii.py", line 1167, in <module>
    app = Application(config_dir, documents_dir, cache_dir, logger,
                      art_to_load or DEFAULT_ART_FILENAME, game_dir_to_load,
                      state_to_load, autoplay_game)
  File "/Users/sourenpapazian/Documents/code/extern/playscii/playscii.py", line 261, in __init__
    GL.glGetIntegerv(GL.GL_MAX_TEXTURE_SIZE, mts)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sourenpapazian/Documents/code/extern/playscii/venv/lib/python3.13/site-packages/OpenGL/latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/Users/sourenpapazian/Documents/code/extern/playscii/venv/lib/python3.13/site-packages/OpenGL/wrapper.py", line 671, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "/Users/sourenpapazian/Documents/code/extern/playscii/venv/lib/python3.13/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
ctypes.ArgumentError: ("argument 2: TypeError: No array-type handler for type _ctypes.CArgObject (value: <cparam 'P' (0x10821c998)>) registered", (GL_MAX_TEXTURE_SIZE, <cparam 'P' (0x10821c998)>))
```

I had to upgrade some libraries to get `pip install -r requirements.txt` to work properly:
```diff
diff --git a/requirements.txt b/requirements.txt
index 8288b3d..03d0c6c 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,6 +1,6 @@
 appdirs==1.4.0
 gprof2dot==2015.12.1
-numpy==1.20.1
-Pillow==8.1.2
-PyOpenGL==3.1.5
+numpy==1.26.4
+Pillow==10.4.0
+PyOpenGL==3.1.7
 PySDL2==0.9.7
```

On Python 3.13.1

**Comment by sourencho** [comment]
Oh i just noticed this but it doesn't really resolve it: https://github.com/orgs/community/discussions/141855
